### ISSUE TITLE
Sample XML file broken link

### ISSUE THREAD

**Issue by adnanhaf** [kuriatsu/carla-scenario#1]
The link on your readme for the sample XML file is broken, it gives me a 404 error. 
https://github.com/kuriatsu/carla-scenario/blob/master/scenario/scenario_town5_base.xml

Please help,

**Comment by kuriatsu** [comment]
Thanks for notifying me.
I updated. 
If you have some trouble, feel free to ask me.

**Comment by adnanhaf** [comment]
@kuriatsu Thank you. I have another question, its actually about your other repository (https://github.com/kuriatsu/ros-bridge)

Are you please able to help me with some questions about it? I apologize for asking here. I tried to create an issue request on the repo but its disabled. Perhaps we can exchange email address to communicate more effectively?

**Comment by kuriatsu** [comment]
OK, please send messages to my account address.
And I enabled issues and discussions on the repo.

**Comment by adnanhaf** [comment]
@kuriatsu I left a issue-comment, please let me know. I can also be reached by email adnanfeez@gmail.com to discuss this further, as I would very much like to get to the bottom of this.

**Comment by kuriatsu** [comment]
OK
