### ISSUE TITLE
Module 'carla' has no attribute 'WalkerBoneControl'

### ISSUE THREAD

**Issue by Ezharjan** [kuriatsu/carla-scenario#3]
_Thanks for your work._

<br>

# Environment
1. Linux Ubuntu 20.04 LTS
2. CARLA 0.9.8
3. Python 3.6.13

# Requirements
I installed the following packages which some of them are either not mentioned in your `requirements.txt` or seemingly mentioned in its name with typo:
 ```bash
pip install x-clip
pip install argparse
pip install pyperclip
pip install pygame
pip install carla
```

# Issue
While I run `python scenario_xml.py -s ./scenario/test.xml`, the error occurs:
```bash
(carla-scenario) root@fst-computer:~/Documents/NewWorks/carla-scenario$ python scenario_xml.py -s ./scenario/test.xml
spawned : 0, 2
spawned : 2, 3
spawned : 4, 4
spawned : 8, 5
spawned : 9, 6
Traceback (most recent call last):
  File "scenario_xml.py", line 552, in <module>
    game_loop(args)
  File "scenario_xml.py", line 502, in game_loop
    sx.poseActor(sx.scenario[0].findall('pose'))
  File "scenario_xml.py", line 251, in poseActor
    control = carla.WalkerBoneControl()
AttributeError: module 'carla' has no attribute 'WalkerBoneControl'
remove 0
remove 2
remove 4
remove 8
remove 9
remove 9
remove debris not in scenario
remove debris not in scenario
remove debris not in scenario
remove debris not in scenario
remove debris not in scenario
```

# Questions
1. **How do we fix the problem of not finding the attribute 'WalkerBoneControl'?**
2. **I guess if this is related to the specific Python version, would you mind informing us about the Python version used for this project?**

_Thanks!_

**Comment by kuriatsu** [comment]
Thanks for finding the issue.
`pip install carla` installs the latest carla and it has WalkerBoneControlIn instead.
 Just changing to `WalkerBoneControlIn` will solve this problem.
https://carla.readthedocs.io/en/0.9.15/python_api/#carlawalkerbonecontrolin

**Comment by Ezharjan** [comment]
> Thanks for finding the issue. `pip install carla` installs the latest carla and it has WalkerBoneControlIn instead. Just changing to `WalkerBoneControlIn` will solve this problem. https://carla.readthedocs.io/en/0.9.15/python_api/#carlawalkerbonecontrolin

Thanks!
I revised it to `WalkerBoneControlIn` as follows:
```python
def poseActor(self, pose_list):
        global carla 
        # control = carla.WalkerBoneControl()
        control = carla.WalkerBoneControlIn(pose_list)
        pose_define = PoseDefine()
        for pose in pose_list:
             ...    
```
But it says that the pose index is out of range:
```bash
Traceback (most recent call last):
  File "scenario_xml.py", line 553, in <module>
    game_loop(args)
  File "scenario_xml.py", line 503, in game_loop
    sx.poseActor(sx.scenario[0].findall('pose'))
  File "scenario_xml.py", line 252, in poseActor
    control = carla.WalkerBoneControlIn(pose_list)
IndexError: child index out of range
```

**Comment by kuriatsu** [comment]
No way...
Then, you need to downgrade to 0.9.8 (pip3 install carla==0.9.8) or remove `<pose>` from the scenario.

**Comment by Ezharjan** [comment]
> No way... Then, you need to downgrade to 0.9.8 (pip3 install carla==0.9.8) or remove `<pose>` from the scenario.

Thanks.
